name: weather_app

description: Flutter Mobile Developer - Evaluation Task 001

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  google_fonts: ^3.0.1
  google_place: ^0.4.7
  http: ^0.13.5
  intl: ^0.17.0
  location: ^4.4.0
  provider: ^6.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
